# Generated by Django 3.2.7 on 2021-10-04 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
